// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: harmonic.bundle.proto

package bundle

import (
	packet "github.com/bloXroute-Labs/solana-trader-proto/harmonic-go/packet"
	shared "github.com/bloXroute-Labs/solana-trader-proto/harmonic-go/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A bundle of transactions to be executed atomically
type Bundle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *shared.Header   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Packets []*packet.Packet `protobuf:"bytes,3,rep,name=packets,proto3" json:"packets,omitempty"`
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_harmonic_bundle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_harmonic_bundle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_harmonic_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *Bundle) GetHeader() *shared.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Bundle) GetPackets() []*packet.Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

var File_harmonic_bundle_proto protoreflect.FileDescriptor

var file_harmonic_bundle_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x1a,
	0x15, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x63,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a,
	0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x28, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x58, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2d, 0x4c, 0x61, 0x62, 0x73, 0x2f, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2d, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x72, 0x6d, 0x6f,
	0x6e, 0x69, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_harmonic_bundle_proto_rawDescOnce sync.Once
	file_harmonic_bundle_proto_rawDescData = file_harmonic_bundle_proto_rawDesc
)

func file_harmonic_bundle_proto_rawDescGZIP() []byte {
	file_harmonic_bundle_proto_rawDescOnce.Do(func() {
		file_harmonic_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(file_harmonic_bundle_proto_rawDescData)
	})
	return file_harmonic_bundle_proto_rawDescData
}

var file_harmonic_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_harmonic_bundle_proto_goTypes = []interface{}{
	(*Bundle)(nil),        // 0: bundle.Bundle
	(*shared.Header)(nil), // 1: shared.Header
	(*packet.Packet)(nil), // 2: packet.Packet
}
var file_harmonic_bundle_proto_depIdxs = []int32{
	1, // 0: bundle.Bundle.header:type_name -> shared.Header
	2, // 1: bundle.Bundle.packets:type_name -> packet.Packet
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_harmonic_bundle_proto_init() }
func file_harmonic_bundle_proto_init() {
	if File_harmonic_bundle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_harmonic_bundle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_harmonic_bundle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_harmonic_bundle_proto_goTypes,
		DependencyIndexes: file_harmonic_bundle_proto_depIdxs,
		MessageInfos:      file_harmonic_bundle_proto_msgTypes,
	}.Build()
	File_harmonic_bundle_proto = out.File
	file_harmonic_bundle_proto_rawDesc = nil
	file_harmonic_bundle_proto_goTypes = nil
	file_harmonic_bundle_proto_depIdxs = nil
}
