# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mev-protos/packet.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class PacketBatch(betterproto.Message):
    packets: List["Packet"] = betterproto.message_field(1)


@dataclass
class Packet(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)
    meta: "Meta" = betterproto.message_field(2)


@dataclass
class Meta(betterproto.Message):
    size: int = betterproto.uint64_field(1)
    addr: str = betterproto.string_field(2)
    port: int = betterproto.uint32_field(3)
    flags: "PacketFlags" = betterproto.message_field(4)
    sender_stake: int = betterproto.uint64_field(5)


@dataclass
class PacketFlags(betterproto.Message):
    discard: bool = betterproto.bool_field(1)
    forwarded: bool = betterproto.bool_field(2)
    repair: bool = betterproto.bool_field(3)
    simple_vote_tx: bool = betterproto.bool_field(4)
    tracer_packet: bool = betterproto.bool_field(5)
