syntax = "proto3";
package api;
option go_package = "github.com/bloXroute-Labs/solana-trader-proto/api";

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/api/field_behavior.proto";
import "google/api/visibility.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "common.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  security: {
    security_requirement: {
      key: "Auth Header";
      value: {
        scope: []
      }
    }
  }
  security_definitions: {
    security: {
      key: "Auth Header";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
      };
    }
  };
  info: {
    title: "Trader API";
    version: "1.6";
    description: "Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.";
    contact: {
      name: "bloXroute Labs Trader API Documentation";
      url: "https://docs.bloxroute.com/solana/trader-api";
      email: "support@bloxroute.com";
    };
  };

  consumes: "application/json";
  produces: "application/json";
};

service Api {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_tag) = {
    external_docs: {
      description: "Detailed API documentation";
      url: "https://bloxroute.gitbook.io/serum-api/about/welcome"
    }
  };

  rpc GetRateLimit(GetRateLimitRequest) returns (GetRateLimitResponse) {
    option (google.api.http) = {
      get: "/api/v2/rate-limit"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns the details of an account rate limits";
      summary: "Returns the details of an account rate limits";
      tags: ["Solana RPC"];
    };
  }

  rpc GetTransactionTrace(GetTransactionTraceRequest) returns (GetTransactionTraceResponse) {
    option (google.api.http) = {
      get: "/api/v2/system/trace"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns the details when a transaction was received, released, and MEV-protection delay information";
      summary: "Returns the details when a transaction was received, released, and MEV-protection delay information";
      tags: ["System"];
    };
  }

  rpc GetTransaction(GetTransactionRequest) returns (GetTransactionResponse) {
    option (google.api.http) = {
      get: "/api/v2/transaction"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns the details of a transaction";
      summary: "Returns the details of a transaction";
      tags: ["Solana RPC"];
    };
  }

  rpc PostSubmitV2(PostSubmitRequest) returns (PostSubmitResponse) {
    option (google.api.http) = {
      post: "/api/v2/submit"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Submits a signed transaction";
      summary: "Transaction submit";
      tags: ["Trade", "Universal"];
    };
  }

  rpc PostSubmitBatchV2(PostSubmitBatchRequest) returns (PostSubmitBatchResponse) {
    option (google.api.http) = {
      post: "/api/v2/submit-batch"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Submits a batch of signed transactions";
      summary: "Transaction batch submit";
      tags: ["Trade", "Universal"];
    };
  }

  rpc PostSubmitSnipeV2(PostSubmitSnipeRequest) returns (PostSubmitSnipeResponse) {
    option (google.api.http) = {
      post: "/api/v2/submit-snipe"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Submits one or two transactions. First one with tip to Jito directly and optionally a tip to BX for super-bundling. Second is propagated as Staked or FastBestEffort";
      summary: "Sniping transactions submit";
      tags: ["Trade", "Universal"];
    };
  }

  rpc PostSubmitPaladinV2(PostSubmitPaladinRequest) returns (PostSubmitResponse) {
    option (google.api.http) = {
      post: "/api/v2/submit-paladin"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Submits a signed transaction to Paladin validators";
      summary: "Transaction submit to Paladin validators";
      tags: ["Trade", "Universal"];
    };
  }

  rpc PostBackrunsV2(PostBackrunsRequest) returns (PostBackrunsResponse) {
    option (google.api.http) = {
      post: "/api/v2/backruns"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Endpoint for OFA partners, to call and confirm a landed backrun and associated information";
      summary: "Backruns";
      tags: ["Trade", "Universal"];
    };
  }

  rpc GetBackrunsV2(GetBackrunsRequest) returns (GetBackrunsResponse) {
    option (google.api.http) = {
      get: "/api/v2/backruns"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns backrun summary grouped by revenue share address for a time range";
      summary: "Backruns summary";
      tags: ["Trade", "Universal"];
    };
  }

  // Raydium V2

  // End of Raydium V2

  // Jupiter V2
  rpc GetJupiterQuotes(GetJupiterQuotesRequest) returns (GetJupiterQuotesResponse) {
    option (google.api.http) = {
      get: "/api/v2/jupiter/quotes"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns quotes from Jupiter";
      summary: "Jupiter Quotes";
      tags: ["Jupiter V2"];
    };
  }

  rpc PostJupiterSwap(PostJupiterSwapRequest) returns (PostJupiterSwapResponse) {
    option (google.api.http) = {
      post: "/api/v2/jupiter/swap"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Generates an unsigned transaction object to make a swap on Jupiter";
      summary: "Unsigned Jupiter swap transaction";
      tags: ["Jupiter V2"];
    };
  }

  rpc PostJupiterSwapInstructions(PostJupiterSwapInstructionsRequest) returns (PostJupiterSwapInstructionsResponse) {
    option (google.api.http) = {
      post: "/api/v2/jupiter/swap-instructions"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Generates an unsigned transaction object using jupiter instructions";
      summary: "Unsigned Jupiter swap transaction from instructions";
      tags: ["Jupiter V2"];
    };
  }

  rpc PostJupiterRouteSwap(PostJupiterRouteSwapRequest) returns (PostJupiterRouteSwapResponse) {
    option(google.api.http) = {
      post: "/api/v2/jupiter/route-swap"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Generates an unsigned transaction object to make a swap on Jupiter on the specified route";
      summary: "Unsigned Jupiter swap transaction along route";
      tags: ["Jupiter V2"];
    };
  }
  // End of Jupiter V2

  //Openbook V2

  //end of Openbook V2

  // system API
  rpc GetServerTime(GetServerTimeRequest) returns (GetServerTimeResponse) {
    option (google.api.http) = {
      get: "/api/v1/system/time"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns current time on the server";
      summary: "Server time";
      tags: "System";
    };
  }

  rpc GetSlotInfo(GetSlotInfoRequest) returns (GetSlotInfoResponse) {
    option (google.api.http) = {
      get: "/api/v2/system/slot-info"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns information about the requested slot. note - limited to 2 epochs before and after current slot";
      summary: "Slot info";
      tags: "System";
    };
  }

  rpc GetRecentBlockHash(GetRecentBlockHashRequest) returns (GetRecentBlockHashResponse) {
    option (google.api.http) = {
      get: "/api/v1/system/blockhash"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns recent block hash";
      summary: "Recent block hash";
      tags: "System";
    };
  }

  rpc GetRecentBlockHashV2(GetRecentBlockHashRequestV2) returns (GetRecentBlockHashResponseV2) {
    option (google.api.http) = {
      get: "/api/v2/system/blockhash"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns recent block hash, supports optional offset";
      summary: "Recent block hash";
      tags: "System";
    };
  }

  rpc GetPriorityFee(GetPriorityFeeRequest) returns (GetPriorityFeeResponse) {
    option (google.api.http) = {
      get: "/api/v2/system/priority-fee"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns an estimated prioritization fee based on recent transactions";
      summary: "Estimated priority fee";
      tags: "System";
    };
  }

  rpc GetPriorityFeeByProgram(GetPriorityFeeByProgramRequest) returns (GetPriorityFeeByProgramResponse) {
    option (google.api.http) = {
      get: "/api/v2/system/priority-fee-by-program"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns an estimated prioritization fee based on recent transactions. supports filtering by program ID";
      summary: "Estimated priority fee";
      tags: "System";
    };
  }

  // account endpoints
  rpc GetAccountBalance(GetAccountBalanceRequest) returns (GetAccountBalanceResponse) {
    option (google.api.http) = {
      get: "/api/v1/account/balance"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns the all token balances for a wallet";
      summary: "Token balances";
      tags: "Account";
    };
  }

  rpc GetTokenAccounts(GetTokenAccountsRequest) returns (GetTokenAccountsResponse) {
    option (google.api.http) = {
      get: "/api/v1/account/token-accounts"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns the all token accounts with their balances for a wallet";
      summary: "Token accounts with balances";
      tags: "Account";
    };
  }

  rpc GetAccountBalanceV2(GetAccountBalanceRequest) returns (GetAccountBalanceResponse) {
    option (google.api.http) = {
      get: "/api/v2/balance"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Returns the all token balances for a wallet";
      summary: "Token balances";
      tags: "Account";
    };
  }

  // trade endpoints
  rpc PostSubmit(PostSubmitRequest) returns (PostSubmitResponse) {
    option (google.api.http) = {
      post: "/api/v1/trade/submit"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Submits a signed transaction";
      summary: "Transaction submit";
      tags: ["Trade", "Universal"];
    };
  }

  rpc PostSubmitBatch(PostSubmitBatchRequest) returns (PostSubmitBatchResponse) {
    option (google.api.http) = {
      post: "/api/v1/trade/submit-batch"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Submits a batch of signed transactions";
      summary: "Transaction batch submit";
      tags: ["Trade", "Universal"];
    };
  }

  // streaming endpoints
  rpc GetRecentBlockHashStream(GetRecentBlockHashRequest) returns (stream GetRecentBlockHashResponse) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "System";
    };
  }

  rpc GetBlockStream(GetBlockStreamRequest) returns (stream GetBlockStreamResponse) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "System";
    };
  }

  rpc GetPriorityFeeStream(GetPriorityFeeRequest) returns (stream GetPriorityFeeResponse) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "System";
    };
  }

  rpc GetPriorityFeeByProgramStream(GetPriorityFeeByProgramRequest) returns (stream GetPriorityFeeByProgramResponse) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "System";
    };
  }

  rpc GetBundleTipStream(GetBundleTipRequest) returns (stream GetBundleTipResponse) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "System";
    };
  }

}

message GetTransactionTraceRequest {
  string signature = 1 [(google.api.field_behavior) = REQUIRED];
}

message GetTransactionTraceResponse {
  string signature = 1;
  google.protobuf.Timestamp firstReceivedTime = 2;
  google.protobuf.Timestamp firstReleasedTime = 3;
  int64 firstReceivedSlot = 4;
  int64 firstReleasedSlot = 5;
  string firstReceivedRegion = 6;
  string firstReleasedRegion = 7;
  bool delayed = 8;
  int64 delayedSlots = 9;
}

message GetServerTimeRequest {}

message GetServerTimeResponse {
  string timestamp = 1;
}

message GetSlotInfoRequest {
  uint64 slot = 1;
}

message GetSlotInfoResponse {
  uint64 slot = 1;
  string leader = 2;
  bool  malicious = 3;
}

message GetAccountBalanceRequest {
  string ownerAddress = 1 [(google.api.field_behavior) = REQUIRED];
}

message GetAccountBalanceResponse {
  repeated TokenBalance tokens = 1;
}

message TokenBalance {
  string symbol = 1;
  string tokenMint = 2;
  double settledAmount = 3;
  double unsettledAmount = 4;
  double openOrdersAmount = 5;
}

message GetTokenAccountsRequest {
  string ownerAddress = 1 [(google.api.field_behavior) = REQUIRED];
}

message GetTokenAccountsResponse {
  repeated TokenAccount accounts = 1;
}

message TokenAccount {
  string symbol = 1;
  string tokenMint = 2;
  string tokenAccount = 3;
  double amount = 4;
}

message TransactionMessage {
  string content = 1;
  bool isCleanup = 2;
}

message TransactionMessageV2 {
  string content = 1;
}

message PostSubmitRequest {
  TransactionMessage transaction = 1 [(google.api.field_behavior) = REQUIRED];
  bool skipPreFlight = 2;
  optional bool frontRunningProtection = 3;
  optional uint64 tip = 4;
  optional bool useStakedRPCs = 6;
  optional bool fastBestEffort = 7 [deprecated = true];
  optional bool allowBackRun = 8;
  optional string revenueAddress = 9;
  optional bool sniping = 10 [deprecated = true];
  optional google.protobuf.Timestamp timestamp = 11;
  optional SubmitProtection submitProtection = 12;
  optional bool revertProtection = 13;
}

message PostSubmitPaladinRequest {
  TransactionMessageV2 transaction = 1 [(google.api.field_behavior) = REQUIRED];
  optional bool revertProtection = 2;
  optional google.protobuf.Timestamp timestamp = 3;

}

message PostSubmitRequestEntry {
  TransactionMessage transaction = 1 [(google.api.field_behavior) = REQUIRED];
  bool skipPreFlight = 2;
}

enum SubmitStrategy {
  P_UKNOWN = 0;
  P_SUBMIT_ALL = 1;
  P_ABORT_ON_FIRST_ERROR = 2;
  P_WAIT_FOR_CONFIRMATION = 3;
}

enum SubmitProtection {
  SP_LOW = 0;
  SP_MEDIUM = 1;
  SP_HIGH = 2;
}

message PostSubmitBatchRequest {
  repeated PostSubmitRequestEntry entries = 1;
  SubmitStrategy submitStrategy = 2 [deprecated = true];
  optional bool useBundle = 3;
  optional bool frontRunningProtection = 4;
  optional google.protobuf.Timestamp timestamp = 5;
  optional SubmitProtection submitProtection = 6;
}

message PostSubmitBatchResponseEntry {
  string signature = 1;
  string error = 2;
  bool submitted = 3;
}

message PostSubmitBatchResponse {
  repeated PostSubmitBatchResponseEntry transactions = 1;
}

message PostSubmitSnipeRequest {
  repeated PostSubmitRequestEntry entries = 1;
  optional bool useStakedRPCs = 2;
  optional google.protobuf.Timestamp timestamp = 3;

}

message PostSubmitSnipeResponse {
  repeated PostSubmitBatchResponseEntry transactions = 1;
}

message PostSubmitResponse {
  string signature = 1;
}

message PostBackrunsRequest {
  string signature = 1 [(google.api.field_behavior) = REQUIRED];
  string backrunSignature = 2 [(google.api.field_behavior) = REQUIRED];
  uint64 revShareLamports = 3 [(google.api.field_behavior) = REQUIRED];
  string revShareAddress = 4 [(google.api.field_behavior) = REQUIRED];
}

message PostBackrunsResponse {
}

message GetBackrunsRequest {
  google.protobuf.Timestamp date = 1;
}

message BackrunResult {
  string revShareAddress = 1;
  double revShareTotalSol = 2;
  uint32 totalBackruns = 3;
}

message GetBackrunsResponse {
  google.protobuf.Timestamp date = 1;
  repeated BackrunResult results = 2;
}

message UnsettledAccountToken {
  string address = 1;
  double amount = 2;
}

message UnsettledAccount {
  string account = 1;
  UnsettledAccountToken baseToken = 2;
  UnsettledAccountToken quoteToken = 3;
}

message GetUnsettledResponse {
  string market = 1;
  repeated UnsettledAccount unsettled = 2;
}

message GetJupiterQuotesRequest{
  string inToken = 1;
  string outToken = 2;
  double inAmount = 3;
  double slippage = 4;
}

message GetJupiterQuotesResponse{
  string inToken = 1;
  string inTokenAddress = 2;
  string outToken = 3;
  string outTokenAddress = 4;
  double inAmount = 5;
  repeated JupiterQuoteRoute routes = 6;
}

message PostJupiterSwapRequest {
  string ownerAddress = 1;
  string inToken = 2;
  string outToken = 3;
  double inAmount = 4;
  double slippage = 5;
  uint32 computeLimit = 6 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: specifies total compute limit to be allocated for all instructions within the created tx"}];
  uint64 computePrice = 7 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: specifies compute price in microlamports to be included as a part of instruction, known as priority fee"}];
  optional uint64 tip = 8 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: Specifies a tip amount that will be used to pay for front-running protection and/or bundle submission services. Minimum value is 1025"}];
}

message PostJupiterSwapInstructionsRequest {
  string ownerAddress = 1;
  string inToken = 2;
  string outToken = 3;
  double inAmount = 4;
  double slippage = 5;
  uint64 computePrice = 7 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: specifies compute price in microlamports to be included as a part of instruction, known as priority fee"}];
  optional uint64 tip = 8 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: Specifies a tip amount that will be used to pay for front-running protection and/or bundle submission services. Minimum value is 1025"}];
}

message PublicKeys {
  repeated string pks = 1;
}

message PostJupiterSwapInstructionsResponse {
  repeated InstructionJupiter instructions = 1;
  map<string, PublicKeys> addressLookupTableAddresses = 2 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Returns a map[publicKey][]publicKey that is used in solana versioned transaction creation."}];
  double outAmount = 3;
  double outAmountMin = 4;
  common.PriceImpactPercentV2 priceImpact = 5;
  repeated common.Fee fees = 6;
}

message PostJupiterSwapResponse{
  repeated TransactionMessage transactions = 1;
  double outAmount = 2;
  double outAmountMin = 3;
  common.PriceImpactPercentV2 priceImpact = 4;
  repeated common.Fee fees = 5;
}

message PostJupiterRouteSwapResponse{
  repeated TransactionMessage transactions = 1;
  double outAmount = 2;
  double outAmountMin = 3;
  common.PriceImpactPercentV2 priceImpact = 4;
  repeated common.Fee fees = 5;
}

message PostJupiterRouteSwapRequest {
  string ownerAddress = 1;
  repeated JupiterRouteStep steps = 2;
  double slippage = 3;
  uint32 computeLimit = 4 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: specifies total compute limit to be allocated for all instructions within the created tx"}];
  uint64 computePrice = 5 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: specifies compute price in microlamports to be included as a part of instruction, known as priority fee"}];
  optional uint64 tip = 6[(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "Optional: Specifies a tip amount that will be used to pay for front-running protection and/or bundle submission services. Minimum value is 1025"}];
}

message JupiterRouteStep {
  string inToken = 1;
  double inAmount = 2;
  string outToken = 3;
  double outAmount = 4;
  double outAmountMin = 5;
  StepProject project = 6;
  common.Fee fee = 7;
}

message RouteStep {
  string inToken = 1;
  double inAmount = 2;
  string outToken = 3;
  double outAmount = 4;
  double outAmountMin = 5;
  StepProject project = 6;
  common.Fee fee = 7;
}

message TradeSwapResponse{
  Project project = 1;
  repeated TransactionMessage transactions = 2;
  double outAmount = 3;
  double outAmountMin = 4;
  common.PriceImpactPercent priceImpact = 5;
  repeated common.Fee fees = 6;
}

enum Project {
  P_UNKNOWN = 0;
  P_ALL = 1;
  P_JUPITER = 2;
  P_RAYDIUM = 3;
  P_SERUM = 4;
  P_OPENBOOK = 5;
}

message JupiterQuoteRoute {
  double inAmount = 1;
  double outAmount = 2;
  double outAmountMin = 3;
  repeated JupiterQuoteStep steps = 4;
}

message JupiterQuoteStep {
  StepProject project = 1;
  string inToken = 2;
  string inTokenAddress = 3;
  string outToken = 4;
  string outTokenAddress = 5;
  double inAmount = 6;
  double outAmount = 7;
  double slippage = 8;
  common.PriceImpactPercentV2 priceImpactPercent = 9;
  common.Fee fee = 10;
  double outAmountMin = 11;
}

message StepProject {
  string label = 1;
  string id = 2;
}

message GetRecentBlockHashRequest {
}

message GetRecentBlockHashResponse {
  string blockHash = 1;
  google.protobuf.Timestamp timestamp = 2;
}

message GetRecentBlockHashRequestV2 {
  uint64 offset = 1;
}

message GetRecentBlockHashResponseV2 {
  string blockHash = 1;
  google.protobuf.Timestamp timestamp = 2;
}

message Block {
  uint64 slot = 1;
  string hash = 2;
  int64 time = 3;
  uint64 height = 4;
}

message GetBlockStreamRequest {
}

message GetBlockStreamResponse {
  Block block = 1;
  google.protobuf.Timestamp timestamp = 2;
}

message GetRateLimitRequest {
}

message GetRateLimitResponse {
  string accountID = 1;
  string tier = 2;
  string interval = 3;
  uint64 intervalNum = 4;
  uint64 limit = 5;
  uint64 count = 6;
  uint64 reset = 7;
  repeated StreamInfo streamInfos = 8;
}

message StreamInfo {
  string streamName = 1;
  string subscriptionID = 2;
  int64 startTime = 3;
  int64 creditUsed = 4;
}

message GetTransactionRequest {
  string signature = 1;
}

message GetTransactionResponse {
  string status = 1;
  TransactionMeta metadata = 2;
  uint64 slot = 3;
  uint64 block_time = 4;
  int32 version = 5;
}

message Instruction {
  uint32 program_id_index = 1;
  repeated uint32 accounts = 2;
  bytes data = 3;
}

message AccountMeta {
  string programID = 1;
  bool isSigner = 2;
  bool isWritable = 3;
}

message InstructionJupiter {
  string programID = 1;
  repeated AccountMeta accounts = 2;
  bytes data = 3;
}

message TransactionMeta {
  string err = 1;
  bool errored = 2;
  uint64 fee = 3;
  repeated uint64 pre_balances = 4;
  repeated uint64 post_balances = 5;
  repeated TransactionMetaInnerInstruction inner_instructions = 6;
  repeated string log_messages = 7;
  repeated TransactionMetaTokenBalance pre_token_balances = 8;
  repeated TransactionMetaTokenBalance post_token_balances = 9;
}

message TransactionMetaInnerInstruction {
  uint32 index = 1;
  repeated Instruction instructions = 2;
}

message TransactionMetaTokenBalance {
  uint32 accountIndex = 1;
  string mint = 2;
  UITokenAmount ui_token_amount = 3;
  string owner = 4;
}

message UITokenAmount {
  double ui_amount = 1;
  uint32 decimals = 2;
  string amount = 3;
  string ui_amount_string = 4;
}

message GetPriorityFeeRequest {
  Project project = 1;
  optional double percentile = 2;
}

message GetPriorityFeeResponse {
  Project project = 1;
  double percentile = 2;
  uint64 feeAtPercentile = 3;
}

message GetPriorityFeeByProgramRequest {
  repeated string programs = 1;
}

message GetPriorityFeeByProgramResponse {
  repeated ProgramPriorityFee data = 1;
}

message ProgramPriorityFee {
  uint64 ten = 1;
  uint64 hundred = 2;
  uint64 fifteen = 3;
  uint64 twenty = 4;
  uint64 twentyFive = 5;
  uint64 thirty = 6;
  uint64 thirtyFive = 7;
  uint64 forty = 8;
  uint64 fortyFive = 9;
  uint64 five = 10;
  uint64 fifty = 11;
  uint64 fiftyFive = 12;
  uint64 sixty = 13;
  uint64 sixtyFive = 14;
  uint64 seventy = 15;
  uint64 seventyFive = 16;
  uint64 eighty = 17;
  uint64 eightyFive = 18;
  uint64 ninety = 19;
  uint64 ninetyFive = 20;
  string program = 21;
}

message GetBundleTipRequest{}

message GetBundleTipResponse {
  google.protobuf.Timestamp timestamp = 1;
  double percentile25 = 2;
  double percentile50 = 3;
  double percentile75 = 4;
  double percentile95 = 5;
  double percentile99 = 6;
  double emaPercentile50 = 7;
}

//Openbook V2 Messages

//End of Openbook V2 Messages
