// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: harmonic.searcher.proto

package searcher

import (
	bundle "github.com/bloXroute-Labs/solana-trader-proto/harmonic-go/bundle"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendBundleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bundle *bundle.Bundle `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
}

func (x *SendBundleRequest) Reset() {
	*x = SendBundleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_harmonic_searcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBundleRequest) ProtoMessage() {}

func (x *SendBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harmonic_searcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBundleRequest.ProtoReflect.Descriptor instead.
func (*SendBundleRequest) Descriptor() ([]byte, []int) {
	return file_harmonic_searcher_proto_rawDescGZIP(), []int{0}
}

func (x *SendBundleRequest) GetBundle() *bundle.Bundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type SendBundleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server-generated UUID for the bundle
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *SendBundleResponse) Reset() {
	*x = SendBundleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_harmonic_searcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBundleResponse) ProtoMessage() {}

func (x *SendBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harmonic_searcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBundleResponse.ProtoReflect.Descriptor instead.
func (*SendBundleResponse) Descriptor() ([]byte, []int) {
	return file_harmonic_searcher_proto_rawDescGZIP(), []int{1}
}

func (x *SendBundleResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_harmonic_searcher_proto protoreflect.FileDescriptor

var file_harmonic_searcher_proto_rawDesc = []byte{
	0x0a, 0x17, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x68, 0x61, 0x72, 0x6d, 0x6f,
	0x6e, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x1a, 0x15, 0x68, 0x61,
	0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x62, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f,
	0x6e, 0x69, 0x63, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x52, 0x06, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x32, 0x6e, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x12, 0x24, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x68, 0x61, 0x72,
	0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x58, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2d, 0x4c, 0x61, 0x62, 0x73,
	0x2f, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2d, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x67, 0x6f,
	0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_harmonic_searcher_proto_rawDescOnce sync.Once
	file_harmonic_searcher_proto_rawDescData = file_harmonic_searcher_proto_rawDesc
)

func file_harmonic_searcher_proto_rawDescGZIP() []byte {
	file_harmonic_searcher_proto_rawDescOnce.Do(func() {
		file_harmonic_searcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_harmonic_searcher_proto_rawDescData)
	})
	return file_harmonic_searcher_proto_rawDescData
}

var file_harmonic_searcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_harmonic_searcher_proto_goTypes = []interface{}{
	(*SendBundleRequest)(nil),  // 0: harmonic.searcher.SendBundleRequest
	(*SendBundleResponse)(nil), // 1: harmonic.searcher.SendBundleResponse
	(*bundle.Bundle)(nil),      // 2: harmonic.bundle.Bundle
}
var file_harmonic_searcher_proto_depIdxs = []int32{
	2, // 0: harmonic.searcher.SendBundleRequest.bundle:type_name -> harmonic.bundle.Bundle
	0, // 1: harmonic.searcher.SearcherService.SendBundle:input_type -> harmonic.searcher.SendBundleRequest
	1, // 2: harmonic.searcher.SearcherService.SendBundle:output_type -> harmonic.searcher.SendBundleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_harmonic_searcher_proto_init() }
func file_harmonic_searcher_proto_init() {
	if File_harmonic_searcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_harmonic_searcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBundleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_harmonic_searcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBundleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_harmonic_searcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harmonic_searcher_proto_goTypes,
		DependencyIndexes: file_harmonic_searcher_proto_depIdxs,
		MessageInfos:      file_harmonic_searcher_proto_msgTypes,
	}.Build()
	File_harmonic_searcher_proto = out.File
	file_harmonic_searcher_proto_rawDesc = nil
	file_harmonic_searcher_proto_goTypes = nil
	file_harmonic_searcher_proto_depIdxs = nil
}
