// source: mev-protos/block.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var mev$protos_shared_pb = require('../mev-protos/shared_pb.js');
goog.object.extend(proto, mev$protos_shared_pb);
goog.exportSymbol('proto.block.CondensedBlock', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.block.CondensedBlock = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.block.CondensedBlock.repeatedFields_, null);
};
goog.inherits(proto.block.CondensedBlock, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.block.CondensedBlock.displayName = 'proto.block.CondensedBlock';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.block.CondensedBlock.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.block.CondensedBlock.prototype.toObject = function(opt_includeInstance) {
  return proto.block.CondensedBlock.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.block.CondensedBlock} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.block.CondensedBlock.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && mev$protos_shared_pb.Header.toObject(includeInstance, f),
    previousBlockhash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    blockhash: jspb.Message.getFieldWithDefault(msg, 3, ""),
    parentSlot: jspb.Message.getFieldWithDefault(msg, 4, 0),
    versionedTransactionsList: msg.getVersionedTransactionsList_asB64(),
    slot: jspb.Message.getFieldWithDefault(msg, 6, 0),
    commitment: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.block.CondensedBlock}
 */
proto.block.CondensedBlock.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.block.CondensedBlock;
  return proto.block.CondensedBlock.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.block.CondensedBlock} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.block.CondensedBlock}
 */
proto.block.CondensedBlock.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new mev$protos_shared_pb.Header;
      reader.readMessage(value,mev$protos_shared_pb.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreviousBlockhash(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockhash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setParentSlot(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addVersionedTransactions(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSlot(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommitment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.block.CondensedBlock.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.block.CondensedBlock.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.block.CondensedBlock} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.block.CondensedBlock.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      mev$protos_shared_pb.Header.serializeBinaryToWriter
    );
  }
  f = message.getPreviousBlockhash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBlockhash();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getParentSlot();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getVersionedTransactionsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      5,
      f
    );
  }
  f = message.getSlot();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getCommitment();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional shared.Header header = 1;
 * @return {?proto.shared.Header}
 */
proto.block.CondensedBlock.prototype.getHeader = function() {
  return /** @type{?proto.shared.Header} */ (
    jspb.Message.getWrapperField(this, mev$protos_shared_pb.Header, 1));
};


/**
 * @param {?proto.shared.Header|undefined} value
 * @return {!proto.block.CondensedBlock} returns this
*/
proto.block.CondensedBlock.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.block.CondensedBlock.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string previous_blockhash = 2;
 * @return {string}
 */
proto.block.CondensedBlock.prototype.getPreviousBlockhash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.setPreviousBlockhash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string blockhash = 3;
 * @return {string}
 */
proto.block.CondensedBlock.prototype.getBlockhash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.setBlockhash = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 parent_slot = 4;
 * @return {number}
 */
proto.block.CondensedBlock.prototype.getParentSlot = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.setParentSlot = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated bytes versioned_transactions = 5;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.block.CondensedBlock.prototype.getVersionedTransactionsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * repeated bytes versioned_transactions = 5;
 * This is a type-conversion wrapper around `getVersionedTransactionsList()`
 * @return {!Array<string>}
 */
proto.block.CondensedBlock.prototype.getVersionedTransactionsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getVersionedTransactionsList()));
};


/**
 * repeated bytes versioned_transactions = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getVersionedTransactionsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.block.CondensedBlock.prototype.getVersionedTransactionsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getVersionedTransactionsList()));
};


/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.setVersionedTransactionsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.addVersionedTransactions = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.clearVersionedTransactionsList = function() {
  return this.setVersionedTransactionsList([]);
};


/**
 * optional uint64 slot = 6;
 * @return {number}
 */
proto.block.CondensedBlock.prototype.getSlot = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.setSlot = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string commitment = 7;
 * @return {string}
 */
proto.block.CondensedBlock.prototype.getCommitment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.block.CondensedBlock} returns this
 */
proto.block.CondensedBlock.prototype.setCommitment = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


goog.object.extend(exports, proto.block);
