// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	GetRateLimit(ctx context.Context, in *GetRateLimitRequest, opts ...grpc.CallOption) (*GetRateLimitResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	PostSubmitV2(ctx context.Context, in *PostSubmitRequest, opts ...grpc.CallOption) (*PostSubmitResponse, error)
	PostSubmitBatchV2(ctx context.Context, in *PostSubmitBatchRequest, opts ...grpc.CallOption) (*PostSubmitBatchResponse, error)
	PostSubmitSnipeV2(ctx context.Context, in *PostSubmitSnipeRequest, opts ...grpc.CallOption) (*PostSubmitSnipeResponse, error)
	PostSubmitPaladinV2(ctx context.Context, in *PostSubmitPaladinRequest, opts ...grpc.CallOption) (*PostSubmitResponse, error)
	// Raydium V2
	GetRaydiumPools(ctx context.Context, in *GetRaydiumPoolsRequest, opts ...grpc.CallOption) (*GetRaydiumPoolsResponse, error)
	GetRaydiumPoolReserve(ctx context.Context, in *GetRaydiumPoolReserveRequest, opts ...grpc.CallOption) (*GetRaydiumPoolReserveResponse, error)
	GetRaydiumQuotes(ctx context.Context, in *GetRaydiumQuotesRequest, opts ...grpc.CallOption) (*GetRaydiumQuotesResponse, error)
	GetRaydiumCPMMQuotes(ctx context.Context, in *GetRaydiumCPMMQuotesRequest, opts ...grpc.CallOption) (*GetRaydiumCPMMQuotesResponse, error)
	GetRaydiumPrices(ctx context.Context, in *GetRaydiumPricesRequest, opts ...grpc.CallOption) (*GetRaydiumPricesResponse, error)
	GetRaydiumCLMMQuotes(ctx context.Context, in *GetRaydiumCLMMQuotesRequest, opts ...grpc.CallOption) (*GetRaydiumCLMMQuotesResponse, error)
	GetRaydiumCLMMPools(ctx context.Context, in *GetRaydiumCLMMPoolsRequest, opts ...grpc.CallOption) (*GetRaydiumCLMMPoolsResponse, error)
	PostRaydiumCLMMSwap(ctx context.Context, in *PostRaydiumSwapRequest, opts ...grpc.CallOption) (*PostRaydiumSwapResponse, error)
	PostRaydiumCLMMRouteSwap(ctx context.Context, in *PostRaydiumRouteSwapRequest, opts ...grpc.CallOption) (*PostRaydiumRouteSwapResponse, error)
	PostRaydiumSwap(ctx context.Context, in *PostRaydiumSwapRequest, opts ...grpc.CallOption) (*PostRaydiumSwapResponse, error)
	PostRaydiumRouteSwap(ctx context.Context, in *PostRaydiumRouteSwapRequest, opts ...grpc.CallOption) (*PostRaydiumRouteSwapResponse, error)
	PostRaydiumCPMMSwap(ctx context.Context, in *PostRaydiumCPMMSwapRequest, opts ...grpc.CallOption) (*PostRaydiumCPMMSwapResponse, error)
	PostRaydiumSwapInstructions(ctx context.Context, in *PostRaydiumSwapInstructionsRequest, opts ...grpc.CallOption) (*PostRaydiumSwapInstructionsResponse, error)
	// Jupiter V2
	GetJupiterQuotes(ctx context.Context, in *GetJupiterQuotesRequest, opts ...grpc.CallOption) (*GetJupiterQuotesResponse, error)
	GetJupiterPrices(ctx context.Context, in *GetJupiterPricesRequest, opts ...grpc.CallOption) (*GetJupiterPricesResponse, error)
	PostJupiterSwap(ctx context.Context, in *PostJupiterSwapRequest, opts ...grpc.CallOption) (*PostJupiterSwapResponse, error)
	PostJupiterSwapInstructions(ctx context.Context, in *PostJupiterSwapInstructionsRequest, opts ...grpc.CallOption) (*PostJupiterSwapInstructionsResponse, error)
	PostJupiterRouteSwap(ctx context.Context, in *PostJupiterRouteSwapRequest, opts ...grpc.CallOption) (*PostJupiterRouteSwapResponse, error)
	// Pump.fun
	GetPumpFunQuotes(ctx context.Context, in *GetPumpFunQuotesRequest, opts ...grpc.CallOption) (*GetPumpFunQuotesResponse, error)
	PostPumpFunSwap(ctx context.Context, in *PostPumpFunSwapRequest, opts ...grpc.CallOption) (*PostPumpFunSwapResponse, error)
	PostPumpFunSwapSol(ctx context.Context, in *PostPumpFunSwapRequestSol, opts ...grpc.CallOption) (*PostPumpFunSwapResponse, error)
	// General
	GetPools(ctx context.Context, in *GetPoolsRequest, opts ...grpc.CallOption) (*GetPoolsResponse, error)
	GetLeaderSchedule(ctx context.Context, in *GetLeaderScheduleRequest, opts ...grpc.CallOption) (*GetLeaderScheduleResponse, error)
	GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*GetPriceResponse, error)
	// system API
	GetServerTime(ctx context.Context, in *GetServerTimeRequest, opts ...grpc.CallOption) (*GetServerTimeResponse, error)
	GetRecentBlockHash(ctx context.Context, in *GetRecentBlockHashRequest, opts ...grpc.CallOption) (*GetRecentBlockHashResponse, error)
	GetRecentBlockHashV2(ctx context.Context, in *GetRecentBlockHashRequestV2, opts ...grpc.CallOption) (*GetRecentBlockHashResponseV2, error)
	GetPriorityFee(ctx context.Context, in *GetPriorityFeeRequest, opts ...grpc.CallOption) (*GetPriorityFeeResponse, error)
	GetPriorityFeeByProgram(ctx context.Context, in *GetPriorityFeeByProgramRequest, opts ...grpc.CallOption) (*GetPriorityFeeByProgramResponse, error)
	GetTokenAccounts(ctx context.Context, in *GetTokenAccountsRequest, opts ...grpc.CallOption) (*GetTokenAccountsResponse, error)
	// trade endpoints
	PostSubmit(ctx context.Context, in *PostSubmitRequest, opts ...grpc.CallOption) (*PostSubmitResponse, error)
	PostSubmitBatch(ctx context.Context, in *PostSubmitBatchRequest, opts ...grpc.CallOption) (*PostSubmitBatchResponse, error)
	// streaming endpoints
	GetRecentBlockHashStream(ctx context.Context, in *GetRecentBlockHashRequest, opts ...grpc.CallOption) (Api_GetRecentBlockHashStreamClient, error)
	GetBlockStream(ctx context.Context, in *GetBlockStreamRequest, opts ...grpc.CallOption) (Api_GetBlockStreamClient, error)
	GetPriorityFeeStream(ctx context.Context, in *GetPriorityFeeRequest, opts ...grpc.CallOption) (Api_GetPriorityFeeStreamClient, error)
	GetPriorityFeeByProgramStream(ctx context.Context, in *GetPriorityFeeByProgramRequest, opts ...grpc.CallOption) (Api_GetPriorityFeeByProgramStreamClient, error)
	GetBundleTipStream(ctx context.Context, in *GetBundleTipRequest, opts ...grpc.CallOption) (Api_GetBundleTipStreamClient, error)
	GetQuotesStream(ctx context.Context, in *GetQuotesStreamRequest, opts ...grpc.CallOption) (Api_GetQuotesStreamClient, error)
	GetPoolReservesStream(ctx context.Context, in *GetPoolReservesStreamRequest, opts ...grpc.CallOption) (Api_GetPoolReservesStreamClient, error)
	GetPricesStream(ctx context.Context, in *GetPricesStreamRequest, opts ...grpc.CallOption) (Api_GetPricesStreamClient, error)
	GetNewRaydiumPoolsStream(ctx context.Context, in *GetNewRaydiumPoolsRequest, opts ...grpc.CallOption) (Api_GetNewRaydiumPoolsStreamClient, error)
	GetNewRaydiumPoolsByTransactionStream(ctx context.Context, in *GetNewRaydiumPoolsByTransactionRequest, opts ...grpc.CallOption) (Api_GetNewRaydiumPoolsByTransactionStreamClient, error)
	GetSwapsStream(ctx context.Context, in *GetSwapsStreamRequest, opts ...grpc.CallOption) (Api_GetSwapsStreamClient, error)
	GetPumpFunSwapsStream(ctx context.Context, in *GetPumpFunSwapsStreamRequest, opts ...grpc.CallOption) (Api_GetPumpFunSwapsStreamClient, error)
	GetPumpFunNewTokensStream(ctx context.Context, in *GetPumpFunNewTokensStreamRequest, opts ...grpc.CallOption) (Api_GetPumpFunNewTokensStreamClient, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetRateLimit(ctx context.Context, in *GetRateLimitRequest, opts ...grpc.CallOption) (*GetRateLimitResponse, error) {
	out := new(GetRateLimitResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRateLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostSubmitV2(ctx context.Context, in *PostSubmitRequest, opts ...grpc.CallOption) (*PostSubmitResponse, error) {
	out := new(PostSubmitResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostSubmitV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostSubmitBatchV2(ctx context.Context, in *PostSubmitBatchRequest, opts ...grpc.CallOption) (*PostSubmitBatchResponse, error) {
	out := new(PostSubmitBatchResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostSubmitBatchV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostSubmitSnipeV2(ctx context.Context, in *PostSubmitSnipeRequest, opts ...grpc.CallOption) (*PostSubmitSnipeResponse, error) {
	out := new(PostSubmitSnipeResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostSubmitSnipeV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostSubmitPaladinV2(ctx context.Context, in *PostSubmitPaladinRequest, opts ...grpc.CallOption) (*PostSubmitResponse, error) {
	out := new(PostSubmitResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostSubmitPaladinV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRaydiumPools(ctx context.Context, in *GetRaydiumPoolsRequest, opts ...grpc.CallOption) (*GetRaydiumPoolsResponse, error) {
	out := new(GetRaydiumPoolsResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRaydiumPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRaydiumPoolReserve(ctx context.Context, in *GetRaydiumPoolReserveRequest, opts ...grpc.CallOption) (*GetRaydiumPoolReserveResponse, error) {
	out := new(GetRaydiumPoolReserveResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRaydiumPoolReserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRaydiumQuotes(ctx context.Context, in *GetRaydiumQuotesRequest, opts ...grpc.CallOption) (*GetRaydiumQuotesResponse, error) {
	out := new(GetRaydiumQuotesResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRaydiumQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRaydiumCPMMQuotes(ctx context.Context, in *GetRaydiumCPMMQuotesRequest, opts ...grpc.CallOption) (*GetRaydiumCPMMQuotesResponse, error) {
	out := new(GetRaydiumCPMMQuotesResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRaydiumCPMMQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRaydiumPrices(ctx context.Context, in *GetRaydiumPricesRequest, opts ...grpc.CallOption) (*GetRaydiumPricesResponse, error) {
	out := new(GetRaydiumPricesResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRaydiumPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRaydiumCLMMQuotes(ctx context.Context, in *GetRaydiumCLMMQuotesRequest, opts ...grpc.CallOption) (*GetRaydiumCLMMQuotesResponse, error) {
	out := new(GetRaydiumCLMMQuotesResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRaydiumCLMMQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRaydiumCLMMPools(ctx context.Context, in *GetRaydiumCLMMPoolsRequest, opts ...grpc.CallOption) (*GetRaydiumCLMMPoolsResponse, error) {
	out := new(GetRaydiumCLMMPoolsResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRaydiumCLMMPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostRaydiumCLMMSwap(ctx context.Context, in *PostRaydiumSwapRequest, opts ...grpc.CallOption) (*PostRaydiumSwapResponse, error) {
	out := new(PostRaydiumSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostRaydiumCLMMSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostRaydiumCLMMRouteSwap(ctx context.Context, in *PostRaydiumRouteSwapRequest, opts ...grpc.CallOption) (*PostRaydiumRouteSwapResponse, error) {
	out := new(PostRaydiumRouteSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostRaydiumCLMMRouteSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostRaydiumSwap(ctx context.Context, in *PostRaydiumSwapRequest, opts ...grpc.CallOption) (*PostRaydiumSwapResponse, error) {
	out := new(PostRaydiumSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostRaydiumSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostRaydiumRouteSwap(ctx context.Context, in *PostRaydiumRouteSwapRequest, opts ...grpc.CallOption) (*PostRaydiumRouteSwapResponse, error) {
	out := new(PostRaydiumRouteSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostRaydiumRouteSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostRaydiumCPMMSwap(ctx context.Context, in *PostRaydiumCPMMSwapRequest, opts ...grpc.CallOption) (*PostRaydiumCPMMSwapResponse, error) {
	out := new(PostRaydiumCPMMSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostRaydiumCPMMSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostRaydiumSwapInstructions(ctx context.Context, in *PostRaydiumSwapInstructionsRequest, opts ...grpc.CallOption) (*PostRaydiumSwapInstructionsResponse, error) {
	out := new(PostRaydiumSwapInstructionsResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostRaydiumSwapInstructions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetJupiterQuotes(ctx context.Context, in *GetJupiterQuotesRequest, opts ...grpc.CallOption) (*GetJupiterQuotesResponse, error) {
	out := new(GetJupiterQuotesResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetJupiterQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetJupiterPrices(ctx context.Context, in *GetJupiterPricesRequest, opts ...grpc.CallOption) (*GetJupiterPricesResponse, error) {
	out := new(GetJupiterPricesResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetJupiterPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostJupiterSwap(ctx context.Context, in *PostJupiterSwapRequest, opts ...grpc.CallOption) (*PostJupiterSwapResponse, error) {
	out := new(PostJupiterSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostJupiterSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostJupiterSwapInstructions(ctx context.Context, in *PostJupiterSwapInstructionsRequest, opts ...grpc.CallOption) (*PostJupiterSwapInstructionsResponse, error) {
	out := new(PostJupiterSwapInstructionsResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostJupiterSwapInstructions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostJupiterRouteSwap(ctx context.Context, in *PostJupiterRouteSwapRequest, opts ...grpc.CallOption) (*PostJupiterRouteSwapResponse, error) {
	out := new(PostJupiterRouteSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostJupiterRouteSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetPumpFunQuotes(ctx context.Context, in *GetPumpFunQuotesRequest, opts ...grpc.CallOption) (*GetPumpFunQuotesResponse, error) {
	out := new(GetPumpFunQuotesResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetPumpFunQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostPumpFunSwap(ctx context.Context, in *PostPumpFunSwapRequest, opts ...grpc.CallOption) (*PostPumpFunSwapResponse, error) {
	out := new(PostPumpFunSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostPumpFunSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostPumpFunSwapSol(ctx context.Context, in *PostPumpFunSwapRequestSol, opts ...grpc.CallOption) (*PostPumpFunSwapResponse, error) {
	out := new(PostPumpFunSwapResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostPumpFunSwapSol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetPools(ctx context.Context, in *GetPoolsRequest, opts ...grpc.CallOption) (*GetPoolsResponse, error) {
	out := new(GetPoolsResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetLeaderSchedule(ctx context.Context, in *GetLeaderScheduleRequest, opts ...grpc.CallOption) (*GetLeaderScheduleResponse, error) {
	out := new(GetLeaderScheduleResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetLeaderSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*GetPriceResponse, error) {
	out := new(GetPriceResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetServerTime(ctx context.Context, in *GetServerTimeRequest, opts ...grpc.CallOption) (*GetServerTimeResponse, error) {
	out := new(GetServerTimeResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetServerTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRecentBlockHash(ctx context.Context, in *GetRecentBlockHashRequest, opts ...grpc.CallOption) (*GetRecentBlockHashResponse, error) {
	out := new(GetRecentBlockHashResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetRecentBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRecentBlockHashV2(ctx context.Context, in *GetRecentBlockHashRequestV2, opts ...grpc.CallOption) (*GetRecentBlockHashResponseV2, error) {
	out := new(GetRecentBlockHashResponseV2)
	err := c.cc.Invoke(ctx, "/api.Api/GetRecentBlockHashV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetPriorityFee(ctx context.Context, in *GetPriorityFeeRequest, opts ...grpc.CallOption) (*GetPriorityFeeResponse, error) {
	out := new(GetPriorityFeeResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetPriorityFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetPriorityFeeByProgram(ctx context.Context, in *GetPriorityFeeByProgramRequest, opts ...grpc.CallOption) (*GetPriorityFeeByProgramResponse, error) {
	out := new(GetPriorityFeeByProgramResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetPriorityFeeByProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetTokenAccounts(ctx context.Context, in *GetTokenAccountsRequest, opts ...grpc.CallOption) (*GetTokenAccountsResponse, error) {
	out := new(GetTokenAccountsResponse)
	err := c.cc.Invoke(ctx, "/api.Api/GetTokenAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostSubmit(ctx context.Context, in *PostSubmitRequest, opts ...grpc.CallOption) (*PostSubmitResponse, error) {
	out := new(PostSubmitResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostSubmit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostSubmitBatch(ctx context.Context, in *PostSubmitBatchRequest, opts ...grpc.CallOption) (*PostSubmitBatchResponse, error) {
	out := new(PostSubmitBatchResponse)
	err := c.cc.Invoke(ctx, "/api.Api/PostSubmitBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRecentBlockHashStream(ctx context.Context, in *GetRecentBlockHashRequest, opts ...grpc.CallOption) (Api_GetRecentBlockHashStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[0], "/api.Api/GetRecentBlockHashStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetRecentBlockHashStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetRecentBlockHashStreamClient interface {
	Recv() (*GetRecentBlockHashResponse, error)
	grpc.ClientStream
}

type apiGetRecentBlockHashStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetRecentBlockHashStreamClient) Recv() (*GetRecentBlockHashResponse, error) {
	m := new(GetRecentBlockHashResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetBlockStream(ctx context.Context, in *GetBlockStreamRequest, opts ...grpc.CallOption) (Api_GetBlockStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[1], "/api.Api/GetBlockStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetBlockStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetBlockStreamClient interface {
	Recv() (*GetBlockStreamResponse, error)
	grpc.ClientStream
}

type apiGetBlockStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetBlockStreamClient) Recv() (*GetBlockStreamResponse, error) {
	m := new(GetBlockStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetPriorityFeeStream(ctx context.Context, in *GetPriorityFeeRequest, opts ...grpc.CallOption) (Api_GetPriorityFeeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[2], "/api.Api/GetPriorityFeeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetPriorityFeeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetPriorityFeeStreamClient interface {
	Recv() (*GetPriorityFeeResponse, error)
	grpc.ClientStream
}

type apiGetPriorityFeeStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetPriorityFeeStreamClient) Recv() (*GetPriorityFeeResponse, error) {
	m := new(GetPriorityFeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetPriorityFeeByProgramStream(ctx context.Context, in *GetPriorityFeeByProgramRequest, opts ...grpc.CallOption) (Api_GetPriorityFeeByProgramStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[3], "/api.Api/GetPriorityFeeByProgramStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetPriorityFeeByProgramStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetPriorityFeeByProgramStreamClient interface {
	Recv() (*GetPriorityFeeByProgramResponse, error)
	grpc.ClientStream
}

type apiGetPriorityFeeByProgramStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetPriorityFeeByProgramStreamClient) Recv() (*GetPriorityFeeByProgramResponse, error) {
	m := new(GetPriorityFeeByProgramResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetBundleTipStream(ctx context.Context, in *GetBundleTipRequest, opts ...grpc.CallOption) (Api_GetBundleTipStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[4], "/api.Api/GetBundleTipStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetBundleTipStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetBundleTipStreamClient interface {
	Recv() (*GetBundleTipResponse, error)
	grpc.ClientStream
}

type apiGetBundleTipStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetBundleTipStreamClient) Recv() (*GetBundleTipResponse, error) {
	m := new(GetBundleTipResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetQuotesStream(ctx context.Context, in *GetQuotesStreamRequest, opts ...grpc.CallOption) (Api_GetQuotesStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[5], "/api.Api/GetQuotesStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetQuotesStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetQuotesStreamClient interface {
	Recv() (*GetQuotesStreamResponse, error)
	grpc.ClientStream
}

type apiGetQuotesStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetQuotesStreamClient) Recv() (*GetQuotesStreamResponse, error) {
	m := new(GetQuotesStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetPoolReservesStream(ctx context.Context, in *GetPoolReservesStreamRequest, opts ...grpc.CallOption) (Api_GetPoolReservesStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[6], "/api.Api/GetPoolReservesStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetPoolReservesStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetPoolReservesStreamClient interface {
	Recv() (*GetPoolReservesStreamResponse, error)
	grpc.ClientStream
}

type apiGetPoolReservesStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetPoolReservesStreamClient) Recv() (*GetPoolReservesStreamResponse, error) {
	m := new(GetPoolReservesStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetPricesStream(ctx context.Context, in *GetPricesStreamRequest, opts ...grpc.CallOption) (Api_GetPricesStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[7], "/api.Api/GetPricesStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetPricesStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetPricesStreamClient interface {
	Recv() (*GetPricesStreamResponse, error)
	grpc.ClientStream
}

type apiGetPricesStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetPricesStreamClient) Recv() (*GetPricesStreamResponse, error) {
	m := new(GetPricesStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetNewRaydiumPoolsStream(ctx context.Context, in *GetNewRaydiumPoolsRequest, opts ...grpc.CallOption) (Api_GetNewRaydiumPoolsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[8], "/api.Api/GetNewRaydiumPoolsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetNewRaydiumPoolsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetNewRaydiumPoolsStreamClient interface {
	Recv() (*GetNewRaydiumPoolsResponse, error)
	grpc.ClientStream
}

type apiGetNewRaydiumPoolsStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetNewRaydiumPoolsStreamClient) Recv() (*GetNewRaydiumPoolsResponse, error) {
	m := new(GetNewRaydiumPoolsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetNewRaydiumPoolsByTransactionStream(ctx context.Context, in *GetNewRaydiumPoolsByTransactionRequest, opts ...grpc.CallOption) (Api_GetNewRaydiumPoolsByTransactionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[9], "/api.Api/GetNewRaydiumPoolsByTransactionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetNewRaydiumPoolsByTransactionStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetNewRaydiumPoolsByTransactionStreamClient interface {
	Recv() (*GetNewRaydiumPoolsByTransactionResponse, error)
	grpc.ClientStream
}

type apiGetNewRaydiumPoolsByTransactionStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetNewRaydiumPoolsByTransactionStreamClient) Recv() (*GetNewRaydiumPoolsByTransactionResponse, error) {
	m := new(GetNewRaydiumPoolsByTransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetSwapsStream(ctx context.Context, in *GetSwapsStreamRequest, opts ...grpc.CallOption) (Api_GetSwapsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[10], "/api.Api/GetSwapsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetSwapsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetSwapsStreamClient interface {
	Recv() (*GetSwapsStreamResponse, error)
	grpc.ClientStream
}

type apiGetSwapsStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetSwapsStreamClient) Recv() (*GetSwapsStreamResponse, error) {
	m := new(GetSwapsStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetPumpFunSwapsStream(ctx context.Context, in *GetPumpFunSwapsStreamRequest, opts ...grpc.CallOption) (Api_GetPumpFunSwapsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[11], "/api.Api/GetPumpFunSwapsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetPumpFunSwapsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetPumpFunSwapsStreamClient interface {
	Recv() (*GetPumpFunSwapsStreamResponse, error)
	grpc.ClientStream
}

type apiGetPumpFunSwapsStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetPumpFunSwapsStreamClient) Recv() (*GetPumpFunSwapsStreamResponse, error) {
	m := new(GetPumpFunSwapsStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) GetPumpFunNewTokensStream(ctx context.Context, in *GetPumpFunNewTokensStreamRequest, opts ...grpc.CallOption) (Api_GetPumpFunNewTokensStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[12], "/api.Api/GetPumpFunNewTokensStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetPumpFunNewTokensStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetPumpFunNewTokensStreamClient interface {
	Recv() (*GetPumpFunNewTokensStreamResponse, error)
	grpc.ClientStream
}

type apiGetPumpFunNewTokensStreamClient struct {
	grpc.ClientStream
}

func (x *apiGetPumpFunNewTokensStreamClient) Recv() (*GetPumpFunNewTokensStreamResponse, error) {
	m := new(GetPumpFunNewTokensStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility
type ApiServer interface {
	GetRateLimit(context.Context, *GetRateLimitRequest) (*GetRateLimitResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	PostSubmitV2(context.Context, *PostSubmitRequest) (*PostSubmitResponse, error)
	PostSubmitBatchV2(context.Context, *PostSubmitBatchRequest) (*PostSubmitBatchResponse, error)
	PostSubmitSnipeV2(context.Context, *PostSubmitSnipeRequest) (*PostSubmitSnipeResponse, error)
	PostSubmitPaladinV2(context.Context, *PostSubmitPaladinRequest) (*PostSubmitResponse, error)
	// Raydium V2
	GetRaydiumPools(context.Context, *GetRaydiumPoolsRequest) (*GetRaydiumPoolsResponse, error)
	GetRaydiumPoolReserve(context.Context, *GetRaydiumPoolReserveRequest) (*GetRaydiumPoolReserveResponse, error)
	GetRaydiumQuotes(context.Context, *GetRaydiumQuotesRequest) (*GetRaydiumQuotesResponse, error)
	GetRaydiumCPMMQuotes(context.Context, *GetRaydiumCPMMQuotesRequest) (*GetRaydiumCPMMQuotesResponse, error)
	GetRaydiumPrices(context.Context, *GetRaydiumPricesRequest) (*GetRaydiumPricesResponse, error)
	GetRaydiumCLMMQuotes(context.Context, *GetRaydiumCLMMQuotesRequest) (*GetRaydiumCLMMQuotesResponse, error)
	GetRaydiumCLMMPools(context.Context, *GetRaydiumCLMMPoolsRequest) (*GetRaydiumCLMMPoolsResponse, error)
	PostRaydiumCLMMSwap(context.Context, *PostRaydiumSwapRequest) (*PostRaydiumSwapResponse, error)
	PostRaydiumCLMMRouteSwap(context.Context, *PostRaydiumRouteSwapRequest) (*PostRaydiumRouteSwapResponse, error)
	PostRaydiumSwap(context.Context, *PostRaydiumSwapRequest) (*PostRaydiumSwapResponse, error)
	PostRaydiumRouteSwap(context.Context, *PostRaydiumRouteSwapRequest) (*PostRaydiumRouteSwapResponse, error)
	PostRaydiumCPMMSwap(context.Context, *PostRaydiumCPMMSwapRequest) (*PostRaydiumCPMMSwapResponse, error)
	PostRaydiumSwapInstructions(context.Context, *PostRaydiumSwapInstructionsRequest) (*PostRaydiumSwapInstructionsResponse, error)
	// Jupiter V2
	GetJupiterQuotes(context.Context, *GetJupiterQuotesRequest) (*GetJupiterQuotesResponse, error)
	GetJupiterPrices(context.Context, *GetJupiterPricesRequest) (*GetJupiterPricesResponse, error)
	PostJupiterSwap(context.Context, *PostJupiterSwapRequest) (*PostJupiterSwapResponse, error)
	PostJupiterSwapInstructions(context.Context, *PostJupiterSwapInstructionsRequest) (*PostJupiterSwapInstructionsResponse, error)
	PostJupiterRouteSwap(context.Context, *PostJupiterRouteSwapRequest) (*PostJupiterRouteSwapResponse, error)
	// Pump.fun
	GetPumpFunQuotes(context.Context, *GetPumpFunQuotesRequest) (*GetPumpFunQuotesResponse, error)
	PostPumpFunSwap(context.Context, *PostPumpFunSwapRequest) (*PostPumpFunSwapResponse, error)
	PostPumpFunSwapSol(context.Context, *PostPumpFunSwapRequestSol) (*PostPumpFunSwapResponse, error)
	// General
	GetPools(context.Context, *GetPoolsRequest) (*GetPoolsResponse, error)
	GetLeaderSchedule(context.Context, *GetLeaderScheduleRequest) (*GetLeaderScheduleResponse, error)
	GetPrice(context.Context, *GetPriceRequest) (*GetPriceResponse, error)
	// system API
	GetServerTime(context.Context, *GetServerTimeRequest) (*GetServerTimeResponse, error)
	GetRecentBlockHash(context.Context, *GetRecentBlockHashRequest) (*GetRecentBlockHashResponse, error)
	GetRecentBlockHashV2(context.Context, *GetRecentBlockHashRequestV2) (*GetRecentBlockHashResponseV2, error)
	GetPriorityFee(context.Context, *GetPriorityFeeRequest) (*GetPriorityFeeResponse, error)
	GetPriorityFeeByProgram(context.Context, *GetPriorityFeeByProgramRequest) (*GetPriorityFeeByProgramResponse, error)
	GetTokenAccounts(context.Context, *GetTokenAccountsRequest) (*GetTokenAccountsResponse, error)
	// trade endpoints
	PostSubmit(context.Context, *PostSubmitRequest) (*PostSubmitResponse, error)
	PostSubmitBatch(context.Context, *PostSubmitBatchRequest) (*PostSubmitBatchResponse, error)
	// streaming endpoints
	GetRecentBlockHashStream(*GetRecentBlockHashRequest, Api_GetRecentBlockHashStreamServer) error
	GetBlockStream(*GetBlockStreamRequest, Api_GetBlockStreamServer) error
	GetPriorityFeeStream(*GetPriorityFeeRequest, Api_GetPriorityFeeStreamServer) error
	GetPriorityFeeByProgramStream(*GetPriorityFeeByProgramRequest, Api_GetPriorityFeeByProgramStreamServer) error
	GetBundleTipStream(*GetBundleTipRequest, Api_GetBundleTipStreamServer) error
	GetQuotesStream(*GetQuotesStreamRequest, Api_GetQuotesStreamServer) error
	GetPoolReservesStream(*GetPoolReservesStreamRequest, Api_GetPoolReservesStreamServer) error
	GetPricesStream(*GetPricesStreamRequest, Api_GetPricesStreamServer) error
	GetNewRaydiumPoolsStream(*GetNewRaydiumPoolsRequest, Api_GetNewRaydiumPoolsStreamServer) error
	GetNewRaydiumPoolsByTransactionStream(*GetNewRaydiumPoolsByTransactionRequest, Api_GetNewRaydiumPoolsByTransactionStreamServer) error
	GetSwapsStream(*GetSwapsStreamRequest, Api_GetSwapsStreamServer) error
	GetPumpFunSwapsStream(*GetPumpFunSwapsStreamRequest, Api_GetPumpFunSwapsStreamServer) error
	GetPumpFunNewTokensStream(*GetPumpFunNewTokensStreamRequest, Api_GetPumpFunNewTokensStreamServer) error
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (UnimplementedApiServer) GetRateLimit(context.Context, *GetRateLimitRequest) (*GetRateLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRateLimit not implemented")
}
func (UnimplementedApiServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedApiServer) PostSubmitV2(context.Context, *PostSubmitRequest) (*PostSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostSubmitV2 not implemented")
}
func (UnimplementedApiServer) PostSubmitBatchV2(context.Context, *PostSubmitBatchRequest) (*PostSubmitBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostSubmitBatchV2 not implemented")
}
func (UnimplementedApiServer) PostSubmitSnipeV2(context.Context, *PostSubmitSnipeRequest) (*PostSubmitSnipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostSubmitSnipeV2 not implemented")
}
func (UnimplementedApiServer) PostSubmitPaladinV2(context.Context, *PostSubmitPaladinRequest) (*PostSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostSubmitPaladinV2 not implemented")
}
func (UnimplementedApiServer) GetRaydiumPools(context.Context, *GetRaydiumPoolsRequest) (*GetRaydiumPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaydiumPools not implemented")
}
func (UnimplementedApiServer) GetRaydiumPoolReserve(context.Context, *GetRaydiumPoolReserveRequest) (*GetRaydiumPoolReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaydiumPoolReserve not implemented")
}
func (UnimplementedApiServer) GetRaydiumQuotes(context.Context, *GetRaydiumQuotesRequest) (*GetRaydiumQuotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaydiumQuotes not implemented")
}
func (UnimplementedApiServer) GetRaydiumCPMMQuotes(context.Context, *GetRaydiumCPMMQuotesRequest) (*GetRaydiumCPMMQuotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaydiumCPMMQuotes not implemented")
}
func (UnimplementedApiServer) GetRaydiumPrices(context.Context, *GetRaydiumPricesRequest) (*GetRaydiumPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaydiumPrices not implemented")
}
func (UnimplementedApiServer) GetRaydiumCLMMQuotes(context.Context, *GetRaydiumCLMMQuotesRequest) (*GetRaydiumCLMMQuotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaydiumCLMMQuotes not implemented")
}
func (UnimplementedApiServer) GetRaydiumCLMMPools(context.Context, *GetRaydiumCLMMPoolsRequest) (*GetRaydiumCLMMPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaydiumCLMMPools not implemented")
}
func (UnimplementedApiServer) PostRaydiumCLMMSwap(context.Context, *PostRaydiumSwapRequest) (*PostRaydiumSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRaydiumCLMMSwap not implemented")
}
func (UnimplementedApiServer) PostRaydiumCLMMRouteSwap(context.Context, *PostRaydiumRouteSwapRequest) (*PostRaydiumRouteSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRaydiumCLMMRouteSwap not implemented")
}
func (UnimplementedApiServer) PostRaydiumSwap(context.Context, *PostRaydiumSwapRequest) (*PostRaydiumSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRaydiumSwap not implemented")
}
func (UnimplementedApiServer) PostRaydiumRouteSwap(context.Context, *PostRaydiumRouteSwapRequest) (*PostRaydiumRouteSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRaydiumRouteSwap not implemented")
}
func (UnimplementedApiServer) PostRaydiumCPMMSwap(context.Context, *PostRaydiumCPMMSwapRequest) (*PostRaydiumCPMMSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRaydiumCPMMSwap not implemented")
}
func (UnimplementedApiServer) PostRaydiumSwapInstructions(context.Context, *PostRaydiumSwapInstructionsRequest) (*PostRaydiumSwapInstructionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRaydiumSwapInstructions not implemented")
}
func (UnimplementedApiServer) GetJupiterQuotes(context.Context, *GetJupiterQuotesRequest) (*GetJupiterQuotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJupiterQuotes not implemented")
}
func (UnimplementedApiServer) GetJupiterPrices(context.Context, *GetJupiterPricesRequest) (*GetJupiterPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJupiterPrices not implemented")
}
func (UnimplementedApiServer) PostJupiterSwap(context.Context, *PostJupiterSwapRequest) (*PostJupiterSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostJupiterSwap not implemented")
}
func (UnimplementedApiServer) PostJupiterSwapInstructions(context.Context, *PostJupiterSwapInstructionsRequest) (*PostJupiterSwapInstructionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostJupiterSwapInstructions not implemented")
}
func (UnimplementedApiServer) PostJupiterRouteSwap(context.Context, *PostJupiterRouteSwapRequest) (*PostJupiterRouteSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostJupiterRouteSwap not implemented")
}
func (UnimplementedApiServer) GetPumpFunQuotes(context.Context, *GetPumpFunQuotesRequest) (*GetPumpFunQuotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPumpFunQuotes not implemented")
}
func (UnimplementedApiServer) PostPumpFunSwap(context.Context, *PostPumpFunSwapRequest) (*PostPumpFunSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostPumpFunSwap not implemented")
}
func (UnimplementedApiServer) PostPumpFunSwapSol(context.Context, *PostPumpFunSwapRequestSol) (*PostPumpFunSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostPumpFunSwapSol not implemented")
}
func (UnimplementedApiServer) GetPools(context.Context, *GetPoolsRequest) (*GetPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPools not implemented")
}
func (UnimplementedApiServer) GetLeaderSchedule(context.Context, *GetLeaderScheduleRequest) (*GetLeaderScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderSchedule not implemented")
}
func (UnimplementedApiServer) GetPrice(context.Context, *GetPriceRequest) (*GetPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedApiServer) GetServerTime(context.Context, *GetServerTimeRequest) (*GetServerTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerTime not implemented")
}
func (UnimplementedApiServer) GetRecentBlockHash(context.Context, *GetRecentBlockHashRequest) (*GetRecentBlockHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentBlockHash not implemented")
}
func (UnimplementedApiServer) GetRecentBlockHashV2(context.Context, *GetRecentBlockHashRequestV2) (*GetRecentBlockHashResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentBlockHashV2 not implemented")
}
func (UnimplementedApiServer) GetPriorityFee(context.Context, *GetPriorityFeeRequest) (*GetPriorityFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriorityFee not implemented")
}
func (UnimplementedApiServer) GetPriorityFeeByProgram(context.Context, *GetPriorityFeeByProgramRequest) (*GetPriorityFeeByProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriorityFeeByProgram not implemented")
}
func (UnimplementedApiServer) GetTokenAccounts(context.Context, *GetTokenAccountsRequest) (*GetTokenAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenAccounts not implemented")
}
func (UnimplementedApiServer) PostSubmit(context.Context, *PostSubmitRequest) (*PostSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostSubmit not implemented")
}
func (UnimplementedApiServer) PostSubmitBatch(context.Context, *PostSubmitBatchRequest) (*PostSubmitBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostSubmitBatch not implemented")
}
func (UnimplementedApiServer) GetRecentBlockHashStream(*GetRecentBlockHashRequest, Api_GetRecentBlockHashStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRecentBlockHashStream not implemented")
}
func (UnimplementedApiServer) GetBlockStream(*GetBlockStreamRequest, Api_GetBlockStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBlockStream not implemented")
}
func (UnimplementedApiServer) GetPriorityFeeStream(*GetPriorityFeeRequest, Api_GetPriorityFeeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPriorityFeeStream not implemented")
}
func (UnimplementedApiServer) GetPriorityFeeByProgramStream(*GetPriorityFeeByProgramRequest, Api_GetPriorityFeeByProgramStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPriorityFeeByProgramStream not implemented")
}
func (UnimplementedApiServer) GetBundleTipStream(*GetBundleTipRequest, Api_GetBundleTipStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBundleTipStream not implemented")
}
func (UnimplementedApiServer) GetQuotesStream(*GetQuotesStreamRequest, Api_GetQuotesStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetQuotesStream not implemented")
}
func (UnimplementedApiServer) GetPoolReservesStream(*GetPoolReservesStreamRequest, Api_GetPoolReservesStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPoolReservesStream not implemented")
}
func (UnimplementedApiServer) GetPricesStream(*GetPricesStreamRequest, Api_GetPricesStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPricesStream not implemented")
}
func (UnimplementedApiServer) GetNewRaydiumPoolsStream(*GetNewRaydiumPoolsRequest, Api_GetNewRaydiumPoolsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNewRaydiumPoolsStream not implemented")
}
func (UnimplementedApiServer) GetNewRaydiumPoolsByTransactionStream(*GetNewRaydiumPoolsByTransactionRequest, Api_GetNewRaydiumPoolsByTransactionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNewRaydiumPoolsByTransactionStream not implemented")
}
func (UnimplementedApiServer) GetSwapsStream(*GetSwapsStreamRequest, Api_GetSwapsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSwapsStream not implemented")
}
func (UnimplementedApiServer) GetPumpFunSwapsStream(*GetPumpFunSwapsStreamRequest, Api_GetPumpFunSwapsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPumpFunSwapsStream not implemented")
}
func (UnimplementedApiServer) GetPumpFunNewTokensStream(*GetPumpFunNewTokensStreamRequest, Api_GetPumpFunNewTokensStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPumpFunNewTokensStream not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_GetRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRateLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRateLimit(ctx, req.(*GetRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostSubmitV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostSubmitV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostSubmitV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostSubmitV2(ctx, req.(*PostSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostSubmitBatchV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSubmitBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostSubmitBatchV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostSubmitBatchV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostSubmitBatchV2(ctx, req.(*PostSubmitBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostSubmitSnipeV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSubmitSnipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostSubmitSnipeV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostSubmitSnipeV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostSubmitSnipeV2(ctx, req.(*PostSubmitSnipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostSubmitPaladinV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSubmitPaladinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostSubmitPaladinV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostSubmitPaladinV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostSubmitPaladinV2(ctx, req.(*PostSubmitPaladinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRaydiumPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaydiumPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRaydiumPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRaydiumPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRaydiumPools(ctx, req.(*GetRaydiumPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRaydiumPoolReserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaydiumPoolReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRaydiumPoolReserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRaydiumPoolReserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRaydiumPoolReserve(ctx, req.(*GetRaydiumPoolReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRaydiumQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaydiumQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRaydiumQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRaydiumQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRaydiumQuotes(ctx, req.(*GetRaydiumQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRaydiumCPMMQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaydiumCPMMQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRaydiumCPMMQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRaydiumCPMMQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRaydiumCPMMQuotes(ctx, req.(*GetRaydiumCPMMQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRaydiumPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaydiumPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRaydiumPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRaydiumPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRaydiumPrices(ctx, req.(*GetRaydiumPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRaydiumCLMMQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaydiumCLMMQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRaydiumCLMMQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRaydiumCLMMQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRaydiumCLMMQuotes(ctx, req.(*GetRaydiumCLMMQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRaydiumCLMMPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaydiumCLMMPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRaydiumCLMMPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRaydiumCLMMPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRaydiumCLMMPools(ctx, req.(*GetRaydiumCLMMPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostRaydiumCLMMSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRaydiumSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostRaydiumCLMMSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostRaydiumCLMMSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostRaydiumCLMMSwap(ctx, req.(*PostRaydiumSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostRaydiumCLMMRouteSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRaydiumRouteSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostRaydiumCLMMRouteSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostRaydiumCLMMRouteSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostRaydiumCLMMRouteSwap(ctx, req.(*PostRaydiumRouteSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostRaydiumSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRaydiumSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostRaydiumSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostRaydiumSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostRaydiumSwap(ctx, req.(*PostRaydiumSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostRaydiumRouteSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRaydiumRouteSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostRaydiumRouteSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostRaydiumRouteSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostRaydiumRouteSwap(ctx, req.(*PostRaydiumRouteSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostRaydiumCPMMSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRaydiumCPMMSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostRaydiumCPMMSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostRaydiumCPMMSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostRaydiumCPMMSwap(ctx, req.(*PostRaydiumCPMMSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostRaydiumSwapInstructions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRaydiumSwapInstructionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostRaydiumSwapInstructions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostRaydiumSwapInstructions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostRaydiumSwapInstructions(ctx, req.(*PostRaydiumSwapInstructionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetJupiterQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJupiterQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetJupiterQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetJupiterQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetJupiterQuotes(ctx, req.(*GetJupiterQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetJupiterPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJupiterPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetJupiterPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetJupiterPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetJupiterPrices(ctx, req.(*GetJupiterPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostJupiterSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostJupiterSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostJupiterSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostJupiterSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostJupiterSwap(ctx, req.(*PostJupiterSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostJupiterSwapInstructions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostJupiterSwapInstructionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostJupiterSwapInstructions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostJupiterSwapInstructions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostJupiterSwapInstructions(ctx, req.(*PostJupiterSwapInstructionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostJupiterRouteSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostJupiterRouteSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostJupiterRouteSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostJupiterRouteSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostJupiterRouteSwap(ctx, req.(*PostJupiterRouteSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetPumpFunQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPumpFunQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetPumpFunQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetPumpFunQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetPumpFunQuotes(ctx, req.(*GetPumpFunQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostPumpFunSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPumpFunSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostPumpFunSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostPumpFunSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostPumpFunSwap(ctx, req.(*PostPumpFunSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostPumpFunSwapSol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPumpFunSwapRequestSol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostPumpFunSwapSol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostPumpFunSwapSol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostPumpFunSwapSol(ctx, req.(*PostPumpFunSwapRequestSol))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetPools(ctx, req.(*GetPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetLeaderSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetLeaderSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetLeaderSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetLeaderSchedule(ctx, req.(*GetLeaderScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetPrice(ctx, req.(*GetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetServerTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetServerTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetServerTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetServerTime(ctx, req.(*GetServerTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRecentBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRecentBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRecentBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRecentBlockHash(ctx, req.(*GetRecentBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRecentBlockHashV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentBlockHashRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRecentBlockHashV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetRecentBlockHashV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRecentBlockHashV2(ctx, req.(*GetRecentBlockHashRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetPriorityFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriorityFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetPriorityFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetPriorityFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetPriorityFee(ctx, req.(*GetPriorityFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetPriorityFeeByProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriorityFeeByProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetPriorityFeeByProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetPriorityFeeByProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetPriorityFeeByProgram(ctx, req.(*GetPriorityFeeByProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetTokenAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetTokenAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetTokenAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetTokenAccounts(ctx, req.(*GetTokenAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostSubmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostSubmit(ctx, req.(*PostSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostSubmitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSubmitBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostSubmitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/PostSubmitBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostSubmitBatch(ctx, req.(*PostSubmitBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRecentBlockHashStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecentBlockHashRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetRecentBlockHashStream(m, &apiGetRecentBlockHashStreamServer{stream})
}

type Api_GetRecentBlockHashStreamServer interface {
	Send(*GetRecentBlockHashResponse) error
	grpc.ServerStream
}

type apiGetRecentBlockHashStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetRecentBlockHashStreamServer) Send(m *GetRecentBlockHashResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlockStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetBlockStream(m, &apiGetBlockStreamServer{stream})
}

type Api_GetBlockStreamServer interface {
	Send(*GetBlockStreamResponse) error
	grpc.ServerStream
}

type apiGetBlockStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetBlockStreamServer) Send(m *GetBlockStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetPriorityFeeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPriorityFeeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetPriorityFeeStream(m, &apiGetPriorityFeeStreamServer{stream})
}

type Api_GetPriorityFeeStreamServer interface {
	Send(*GetPriorityFeeResponse) error
	grpc.ServerStream
}

type apiGetPriorityFeeStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetPriorityFeeStreamServer) Send(m *GetPriorityFeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetPriorityFeeByProgramStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPriorityFeeByProgramRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetPriorityFeeByProgramStream(m, &apiGetPriorityFeeByProgramStreamServer{stream})
}

type Api_GetPriorityFeeByProgramStreamServer interface {
	Send(*GetPriorityFeeByProgramResponse) error
	grpc.ServerStream
}

type apiGetPriorityFeeByProgramStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetPriorityFeeByProgramStreamServer) Send(m *GetPriorityFeeByProgramResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetBundleTipStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBundleTipRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetBundleTipStream(m, &apiGetBundleTipStreamServer{stream})
}

type Api_GetBundleTipStreamServer interface {
	Send(*GetBundleTipResponse) error
	grpc.ServerStream
}

type apiGetBundleTipStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetBundleTipStreamServer) Send(m *GetBundleTipResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetQuotesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetQuotesStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetQuotesStream(m, &apiGetQuotesStreamServer{stream})
}

type Api_GetQuotesStreamServer interface {
	Send(*GetQuotesStreamResponse) error
	grpc.ServerStream
}

type apiGetQuotesStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetQuotesStreamServer) Send(m *GetQuotesStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetPoolReservesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPoolReservesStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetPoolReservesStream(m, &apiGetPoolReservesStreamServer{stream})
}

type Api_GetPoolReservesStreamServer interface {
	Send(*GetPoolReservesStreamResponse) error
	grpc.ServerStream
}

type apiGetPoolReservesStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetPoolReservesStreamServer) Send(m *GetPoolReservesStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetPricesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPricesStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetPricesStream(m, &apiGetPricesStreamServer{stream})
}

type Api_GetPricesStreamServer interface {
	Send(*GetPricesStreamResponse) error
	grpc.ServerStream
}

type apiGetPricesStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetPricesStreamServer) Send(m *GetPricesStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetNewRaydiumPoolsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNewRaydiumPoolsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetNewRaydiumPoolsStream(m, &apiGetNewRaydiumPoolsStreamServer{stream})
}

type Api_GetNewRaydiumPoolsStreamServer interface {
	Send(*GetNewRaydiumPoolsResponse) error
	grpc.ServerStream
}

type apiGetNewRaydiumPoolsStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetNewRaydiumPoolsStreamServer) Send(m *GetNewRaydiumPoolsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetNewRaydiumPoolsByTransactionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNewRaydiumPoolsByTransactionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetNewRaydiumPoolsByTransactionStream(m, &apiGetNewRaydiumPoolsByTransactionStreamServer{stream})
}

type Api_GetNewRaydiumPoolsByTransactionStreamServer interface {
	Send(*GetNewRaydiumPoolsByTransactionResponse) error
	grpc.ServerStream
}

type apiGetNewRaydiumPoolsByTransactionStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetNewRaydiumPoolsByTransactionStreamServer) Send(m *GetNewRaydiumPoolsByTransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetSwapsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSwapsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetSwapsStream(m, &apiGetSwapsStreamServer{stream})
}

type Api_GetSwapsStreamServer interface {
	Send(*GetSwapsStreamResponse) error
	grpc.ServerStream
}

type apiGetSwapsStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetSwapsStreamServer) Send(m *GetSwapsStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetPumpFunSwapsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPumpFunSwapsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetPumpFunSwapsStream(m, &apiGetPumpFunSwapsStreamServer{stream})
}

type Api_GetPumpFunSwapsStreamServer interface {
	Send(*GetPumpFunSwapsStreamResponse) error
	grpc.ServerStream
}

type apiGetPumpFunSwapsStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetPumpFunSwapsStreamServer) Send(m *GetPumpFunSwapsStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_GetPumpFunNewTokensStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPumpFunNewTokensStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetPumpFunNewTokensStream(m, &apiGetPumpFunNewTokensStreamServer{stream})
}

type Api_GetPumpFunNewTokensStreamServer interface {
	Send(*GetPumpFunNewTokensStreamResponse) error
	grpc.ServerStream
}

type apiGetPumpFunNewTokensStreamServer struct {
	grpc.ServerStream
}

func (x *apiGetPumpFunNewTokensStreamServer) Send(m *GetPumpFunNewTokensStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRateLimit",
			Handler:    _Api_GetRateLimit_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _Api_GetTransaction_Handler,
		},
		{
			MethodName: "PostSubmitV2",
			Handler:    _Api_PostSubmitV2_Handler,
		},
		{
			MethodName: "PostSubmitBatchV2",
			Handler:    _Api_PostSubmitBatchV2_Handler,
		},
		{
			MethodName: "PostSubmitSnipeV2",
			Handler:    _Api_PostSubmitSnipeV2_Handler,
		},
		{
			MethodName: "PostSubmitPaladinV2",
			Handler:    _Api_PostSubmitPaladinV2_Handler,
		},
		{
			MethodName: "GetRaydiumPools",
			Handler:    _Api_GetRaydiumPools_Handler,
		},
		{
			MethodName: "GetRaydiumPoolReserve",
			Handler:    _Api_GetRaydiumPoolReserve_Handler,
		},
		{
			MethodName: "GetRaydiumQuotes",
			Handler:    _Api_GetRaydiumQuotes_Handler,
		},
		{
			MethodName: "GetRaydiumCPMMQuotes",
			Handler:    _Api_GetRaydiumCPMMQuotes_Handler,
		},
		{
			MethodName: "GetRaydiumPrices",
			Handler:    _Api_GetRaydiumPrices_Handler,
		},
		{
			MethodName: "GetRaydiumCLMMQuotes",
			Handler:    _Api_GetRaydiumCLMMQuotes_Handler,
		},
		{
			MethodName: "GetRaydiumCLMMPools",
			Handler:    _Api_GetRaydiumCLMMPools_Handler,
		},
		{
			MethodName: "PostRaydiumCLMMSwap",
			Handler:    _Api_PostRaydiumCLMMSwap_Handler,
		},
		{
			MethodName: "PostRaydiumCLMMRouteSwap",
			Handler:    _Api_PostRaydiumCLMMRouteSwap_Handler,
		},
		{
			MethodName: "PostRaydiumSwap",
			Handler:    _Api_PostRaydiumSwap_Handler,
		},
		{
			MethodName: "PostRaydiumRouteSwap",
			Handler:    _Api_PostRaydiumRouteSwap_Handler,
		},
		{
			MethodName: "PostRaydiumCPMMSwap",
			Handler:    _Api_PostRaydiumCPMMSwap_Handler,
		},
		{
			MethodName: "PostRaydiumSwapInstructions",
			Handler:    _Api_PostRaydiumSwapInstructions_Handler,
		},
		{
			MethodName: "GetJupiterQuotes",
			Handler:    _Api_GetJupiterQuotes_Handler,
		},
		{
			MethodName: "GetJupiterPrices",
			Handler:    _Api_GetJupiterPrices_Handler,
		},
		{
			MethodName: "PostJupiterSwap",
			Handler:    _Api_PostJupiterSwap_Handler,
		},
		{
			MethodName: "PostJupiterSwapInstructions",
			Handler:    _Api_PostJupiterSwapInstructions_Handler,
		},
		{
			MethodName: "PostJupiterRouteSwap",
			Handler:    _Api_PostJupiterRouteSwap_Handler,
		},
		{
			MethodName: "GetPumpFunQuotes",
			Handler:    _Api_GetPumpFunQuotes_Handler,
		},
		{
			MethodName: "PostPumpFunSwap",
			Handler:    _Api_PostPumpFunSwap_Handler,
		},
		{
			MethodName: "PostPumpFunSwapSol",
			Handler:    _Api_PostPumpFunSwapSol_Handler,
		},
		{
			MethodName: "GetPools",
			Handler:    _Api_GetPools_Handler,
		},
		{
			MethodName: "GetLeaderSchedule",
			Handler:    _Api_GetLeaderSchedule_Handler,
		},
		{
			MethodName: "GetPrice",
			Handler:    _Api_GetPrice_Handler,
		},
		{
			MethodName: "GetServerTime",
			Handler:    _Api_GetServerTime_Handler,
		},
		{
			MethodName: "GetRecentBlockHash",
			Handler:    _Api_GetRecentBlockHash_Handler,
		},
		{
			MethodName: "GetRecentBlockHashV2",
			Handler:    _Api_GetRecentBlockHashV2_Handler,
		},
		{
			MethodName: "GetPriorityFee",
			Handler:    _Api_GetPriorityFee_Handler,
		},
		{
			MethodName: "GetPriorityFeeByProgram",
			Handler:    _Api_GetPriorityFeeByProgram_Handler,
		},
		{
			MethodName: "GetTokenAccounts",
			Handler:    _Api_GetTokenAccounts_Handler,
		},
		{
			MethodName: "PostSubmit",
			Handler:    _Api_PostSubmit_Handler,
		},
		{
			MethodName: "PostSubmitBatch",
			Handler:    _Api_PostSubmitBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRecentBlockHashStream",
			Handler:       _Api_GetRecentBlockHashStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBlockStream",
			Handler:       _Api_GetBlockStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPriorityFeeStream",
			Handler:       _Api_GetPriorityFeeStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPriorityFeeByProgramStream",
			Handler:       _Api_GetPriorityFeeByProgramStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBundleTipStream",
			Handler:       _Api_GetBundleTipStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetQuotesStream",
			Handler:       _Api_GetQuotesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPoolReservesStream",
			Handler:       _Api_GetPoolReservesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPricesStream",
			Handler:       _Api_GetPricesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNewRaydiumPoolsStream",
			Handler:       _Api_GetNewRaydiumPoolsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNewRaydiumPoolsByTransactionStream",
			Handler:       _Api_GetNewRaydiumPoolsByTransactionStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSwapsStream",
			Handler:       _Api_GetSwapsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPumpFunSwapsStream",
			Handler:       _Api_GetPumpFunSwapsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPumpFunNewTokensStream",
			Handler:       _Api_GetPumpFunNewTokensStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
